### ISSUE TITLE
time varying parameters

### ISSUE THREAD

**Issue by snailittle** [nlmixrdevelopment/nlmixr-examples#1]
How do I define a clearance that changes with time:
I am trying to implement this function in "fo" or "saem" so that Clearance decrease over time to near 0:  

```r
CL=tvCL * exp(-Kdes*time) * exp(ETA.CL)
```

**Comment by mattfidler** [comment]
Both can be supported.  You can use the above expression in `focei`

If you want to use this in `saem`:

```r
CLa = exp(tvCL+ ETA.CL)
...
CL = exp(-Kdes * time) * CLa
```
